from os import getenv
from dotenv import load_dotenv


load_dotenv()


class Settings():
    EVERNOTE_CONSUMER_KEY = getenv('EVERNOTE_CONSUMER_KEY')
    EVERNOTE_CONSUMER_SECRET = getenv('EVERNOTE_CONSUMER_SECRET')
    EVERNOTE_PERSONAL_TOKEN = getenv('EVERNOTE_PERSONAL_TOKEN')

    JOURNAL_TEMPLATE_NOTE_GUID = getenv('JOURNAL_TEMPLATE_NOTE_GUID')
    JOURNAL_NOTEBOOK_GUID = getenv('JOURNAL_NOTEBOOK_GUID')

    INBOX_NOTEBOOK_GUID = getenv('INBOX_NOTEBOOK_GUID')
    
